name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on:
    # –°–æ–±—ã—Ç–∏—è, –∫–æ—Ç–æ—Ä—ã–µ –∑–∞–ø—É—Å–∫–∞—é—Ç jobs
     push:
       branches: [ "main" ]
     pull_request:
       branches: [ "main" ]
# jobs –∑–∞–ø—É—Å–∫–∞—é—Ç—Å—è –ø–∞—Ä–∞–ª–ª–µ–ª—å–Ω–æ, –µ—Å–ª–∏ –Ω–µ —É–∫–∞–∑–∞–Ω–∞ –ø–æ—Å–ª–µ–¥–æ–≤–∞—Ç–µ–ª—å–Ω–æ—Å—Ç—å
jobs:
    # –ù–∞–∑–≤–∞–Ω–∏–µ job –≤—ã –º–æ–∂–µ—Ç–µ –Ω–∞–∑–≤–∞—Ç—å –∫–∞–∫ —É–≥–æ–¥–Ω–æ
    my_build_job:
      # –û–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω–∞—è —Å–∏—Å—Ç–µ–º–∞ –≤ –≤–∏—Ä—Ç—É–∞–ª—å–Ω–æ–π –º–∞—à–∏–Ω–µ, –≤ –∫–æ—Ç–æ—Ä–æ–π –∑–∞–ø—É—Å–∫–∞—é—Ç—Å—è –ø—Ä–æ—Ü–µ—Å—Å—ã
      runs-on: ubuntu-latest
        # –®–∞–≥–∏
        steps:
          # Actions –æ—Ç github: –ø—Ä–æ–≤–µ—Ä—è–µ—Ç —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π, –≥–∏—Ç –∏ —Ç.–¥.
          - uses: actions/checkout@v3

          # –ü—Ä–∏–º–µ—Ä –æ–¥–Ω–æ–ª–∏–Ω–µ–π–Ω–æ–≥–æ –ø—Ä–æ—Å—Ç–æ–≥–æ —Å–∫—Ä–∏–ø—Ç–∞ shell
          - name: Run a one-line script
            run: echo Hello, world!

          # –ü—Ä–∏–º–µ—Ä –º–Ω–æ–≥–æ–ª–∏–Ω–µ–π–Ω–æ–≥–æ —Å–∫—Ä–∏–ø—Ç–∞ shell
          - name: Run a multi-line script
            run: |
                echo Add other actions to build,
                echo test, and deploy your project.